/**
 * Shared types for the Thuishaven MCP server.
 * These mirror schema/pattern.schema.json — keep both in sync.
 */

export type PatternStatus = "stable" | "experimental" | "deprecated";

export type PatternCategory =
  | "bootstrap"
  | "productivity"
  | "collaboration"
  | "media"
  | "security"
  | "monitoring"
  | "family";

export type DeployTarget = "dokploy" | "docker-compose" | "coolify" | "k8s";

export type ExposureModel =
  | "public-domain"
  | "tailnet"
  | "cloudflare-tunnel"
  | "local-only";

export interface Recommendation {
  app: string;
  app_source: string;
  deploy_target: DeployTarget;
  exposure: ExposureModel;
}

export interface Alternative {
  name: string;
  reason_not_chosen: string;
}

export interface PatternFrontmatter {
  id: string;
  title: string;
  version: number;
  status: PatternStatus;
  category: PatternCategory;
  tags: string[];
  maintainer: string;
  problem: string;
  recommendation: Recommendation;
  alternatives: Alternative[];
  prerequisites: string[];
  estimated_time_minutes: number;
  gotchas: string[];
  related: string[];
}

/** A fully loaded, validated pattern. */
export interface Pattern {
  frontmatter: PatternFrontmatter;
  body: string;
}

/**
 * Raw pattern source before validation: what the filesystem loader and the
 * build-time bundle both produce. `frontmatter` is unknown until validated.
 */
export interface PatternSource {
  filename: string;
  frontmatter: unknown;
  body: string;
}

/** Shape of src/patterns.bundle.json, generated by scripts/build-patterns-bundle.ts. */
export interface PatternsBundle {
  patterns: Pattern[];
}

/** Category descriptions, from the spec's allowed-categories list. */
export const CATEGORY_DESCRIPTIONS: Record<PatternCategory, string> = {
  bootstrap: "Server-level setup (Docker, Dokploy, Tailscale)",
  productivity: "Notes, tasks, bookmarks",
  collaboration: "Shared tools (date pickers, expense splitting)",
  media: "Photos, music, video",
  security: "Password managers, 2FA, secrets",
  monitoring: "Uptime, logs, metrics",
  family: "Opinionated multi-user setups for households",
};

export const ALL_CATEGORIES = Object.keys(
  CATEGORY_DESCRIPTIONS,
) as PatternCategory[];

/** GitHub URL prefix used to build get_pattern's source_url. */
export const PATTERN_SOURCE_BASE_URL =
  "https://github.com/thuishaven/thuishaven/blob/main/patterns";

/** Error thrown by tools for invalid input (unknown id, unknown target, ...). */
export class ToolError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ToolError";
  }
}
